README.rst
docs/source/all.rst
docs/source/sg_execution_times.rst
docs/source/torchdr.user_guide.rst
torchdr/__init__.py
torchdr/affinity/entropic.py
torchdr/affinity/simple.py
torchdr/neighbor_embedding/__init__.py
torchdr/neighbor_embedding/base.py
torchdr/neighbor_embedding/snekhorn.py
torchdr/tests/test_estimators.py
torchdr/tests/test_neighbor_embedding.py

This PR implements the SNEkhorn algorithm.
Fixes #34 .

[Feature] SNEkhorn / TSNEkhorn

---

torchdr/__init__.py
torchdr/affinity_matcher.py
torchdr/neighbor_embedding/__init__.py
torchdr/neighbor_embedding/base.py
torchdr/neighbor_embedding/largevis.py
torchdr/neighbor_embedding/ncsne.py
torchdr/tests/test_estimators.py
torchdr/tests/test_neighbor_embedding.py
torchdr/utils/__init__.py
torchdr/utils/losses.py
torchdr/utils/utils.py
torchdr/utils/wrappers.py

This PR implements the LargeVis algorithm.
Fixes #36 .

[Feature] LargeVis

---

torchdr/__init__.py
torchdr/affinity/entropic.py
torchdr/affinity/knn_normalized.py
torchdr/affinity/umap.py
torchdr/neighbor_embedding/__init__.py
torchdr/neighbor_embedding/base.py
torchdr/neighbor_embedding/snekhorn.py
torchdr/neighbor_embedding/umap.py
torchdr/tests/test_neighbor_embedding.py

[Feature] UMAP algorithm

---

torchdr/tests/test_affinity.py
torchdr/tests/test_neighbor_embedding.py
torchdr/tests/utils.py

Duplicated functions (with different returns here) are error prone

[BugFix] CLN single implem of duplicated `toy_dataset` function

---

CODE_OF_CONDUCT.md

[Feature] Create CODE_OF_CONDUCT.md

---

README.rst
RELEASES.rst
pyproject.toml
torchdr/affinity/entropic.py
torchdr/affinity/knn_normalized.py
torchdr/affinity/quadratic.py
torchdr/affinity/umap.py
torchdr/eval.py
torchdr/neighbor_embedding/largevis.py
torchdr/neighbor_embedding/ncsne.py
torchdr/neighbor_embedding/sne.py
torchdr/neighbor_embedding/tsne.py
torchdr/neighbor_embedding/tsnekhorn.py
torchdr/neighbor_embedding/umap.py

[Doc] change citation style from numbers to Author-Year

---

README.rst

[Doc] badge for the doc

---

README.rst
RELEASES.rst
docs/source/conf.py
docs/source/index.rst
docs/source/references.bib
docs/source/torchdr.bibliography.rst
pyproject.toml
torchdr/affinity/entropic.py
torchdr/affinity/quadratic.py
torchdr/affinity/umap.py
torchdr/eval.py
torchdr/neighbor_embedding/base.py
torchdr/neighbor_embedding/largevis.py
torchdr/neighbor_embedding/ncsne.py
torchdr/neighbor_embedding/sne.py
torchdr/neighbor_embedding/tsne.py
torchdr/neighbor_embedding/tsnekhorn.py
torchdr/neighbor_embedding/umap.py

[Doc] proper handling of the biblio via sphinx

---

docs/source/all.rst
docs/source/torchdr.user_guide.rst
torchdr/affinity/knn_normalized.py

[BugFix] make the doc consistent with new biblio

---

docs/source/torchdr.contributing.rst

[Doc] PR status guidelines

---

.github/PULL_REQUEST_TEMPLATE.md

[Minor] simplify PR template

---

.github/workflows/testing.yml

[BugFix] simplify testing workflow with conda

---

examples/images/cifar10.py
examples/images/cifar100.py
pyproject.toml
torchdr/affinity_matcher.py
torchdr/neighbor_embedding/base.py
torchdr/neighbor_embedding/infotsne.py
torchdr/neighbor_embedding/largevis.py
torchdr/neighbor_embedding/sne.py
torchdr/neighbor_embedding/tsne.py
torchdr/neighbor_embedding/tsnekhorn.py
torchdr/neighbor_embedding/umap.py
torchdr/tests/test_affinity_matcher.py
torchdr/tests/test_neighbor_embedding.py

[Naming] tol -> min_grad_norm, remove tolog

---

README.rst
RELEASES.rst
benchmarks/benchmark_umap.py
torchdr/affinity_matcher.py

[Feature] UMAP benchmark

---

torchdr/__about__.py

[Version] 0.2

---

torchdr/affinity/entropic.py
torchdr/affinity/quadratic.py
torchdr/affinity_matcher.py
torchdr/neighbor_embedding/base.py
torchdr/neighbor_embedding/infotsne.py
torchdr/neighbor_embedding/largevis.py
torchdr/neighbor_embedding/sne.py
torchdr/neighbor_embedding/tsne.py
torchdr/neighbor_embedding/tsnekhorn.py
torchdr/neighbor_embedding/umap.py
torchdr/tests/test_affinity_matcher.py
torchdr/utils/__init__.py
torchdr/utils/optim.py

[Feature] optimizer and scheduler can be any torch optimizer and scheduler

---

torchdr/tests/test_affinity_matcher.py

[CodeCov] tests for AffinityMatcher

---

.github/workflows/testing.yml

[CodeCov] Full test with Python 3.10

---

benchmarks/benchmark_umap.py
pyproject.toml
torchdr/affinity/base.py
torchdr/base.py
torchdr/neighbor_embedding/tsnekhorn.py
torchdr/tests/test_estimators.py
torchdr/utils/__init__.py
torchdr/utils/faiss.py
torchdr/utils/keops.py
torchdr/utils/utils.py

[BugFix] PyKeops & Faiss import error

---

docs/source/all.rst
docs/source/references.bib
examples/basics/demo_ne_methods_affinity_matcher.py
torchdr/__init__.py
torchdr/affinity/__init__.py
torchdr/affinity/base.py
torchdr/affinity/entropic.py
torchdr/affinity/pacmap.py
torchdr/affinity/umap.py
torchdr/affinity/unnormalized.py
torchdr/affinity_matcher.py
torchdr/neighbor_embedding/__init__.py
torchdr/neighbor_embedding/base.py
torchdr/neighbor_embedding/cosne.py
torchdr/neighbor_embedding/infotsne.py
torchdr/neighbor_embedding/largevis.py
torchdr/neighbor_embedding/pacmap.py
torchdr/neighbor_embedding/sne.py
torchdr/neighbor_embedding/tsne.py
torchdr/neighbor_embedding/tsnekhorn.py
torchdr/neighbor_embedding/umap.py
torchdr/tests/test_affinity.py
torchdr/tests/test_affinity_matcher.py
torchdr/tests/test_neighbor_embedding.py
torchdr/utils/__init__.py
torchdr/utils/optim.py
torchdr/utils/utils.py
torchdr/utils/validation.py
torchdr/utils/wrappers.py

[Feature] PACMAP algorithm

---

torchdr/affinity/base.py
torchdr/affinity/entropic.py
torchdr/affinity/pacmap.py
torchdr/affinity/phate.py
torchdr/affinity/quadratic.py
torchdr/affinity/umap.py
torchdr/affinity_matcher.py
torchdr/base.py
torchdr/clustering.py
torchdr/neighbor_embedding/pacmap.py
torchdr/spectral_embedding/incremental_pca.py
torchdr/spectral_embedding/kernel_pca.py
torchdr/spectral_embedding/pca.py
torchdr/tests/test_affinity_matcher.py
torchdr/tests/test_estimators.py
torchdr/utils/__init__.py
torchdr/utils/root_search.py
torchdr/utils/utils.py

[Feature] Standardize Logging

---

torchdr/affinity_matcher.py
torchdr/base.py
torchdr/spectral_embedding/incremental_pca.py
torchdr/spectral_embedding/kernel_pca.py
torchdr/spectral_embedding/pca.py

[Feature] Align DRModule with scikit-learn and improve type hints

---

README.md
examples/affinities/demo_ea_adaptivity.py
torchdr/__init__.py
torchdr/affinity/__init__.py
torchdr/affinity/base.py
torchdr/affinity/entropic.py
torchdr/affinity/knn_normalized.py
torchdr/affinity_matcher.py
torchdr/distance/base.py
torchdr/distance/faiss.py
torchdr/distance/keops.py
torchdr/distance/torch.py
torchdr/neighbor_embedding/base.py
torchdr/neighbor_embedding/cosne.py
torchdr/neighbor_embedding/infotsne.py
torchdr/neighbor_embedding/largevis.py
torchdr/neighbor_embedding/pacmap.py
torchdr/neighbor_embedding/sne.py
torchdr/neighbor_embedding/tsne.py
torchdr/neighbor_embedding/tsnekhorn.py
torchdr/neighbor_embedding/umap.py
torchdr/spectral_embedding/phate.py
torchdr/tests/test_affinity.py
torchdr/tests/test_affinity_matcher.py
torchdr/tests/test_neighbor_embedding.py
torchdr/tests/test_utils.py
torchdr/utils/root_search.py
torchdr/utils/sparse.py
torchdr/utils/validation.py

[Feature] allow direct gradient computation

---

README.md
RELEASES.rst

[Doc] update releases

---

torchdr/__about__.py

[Version] 0.3 

---

torchdr/utils/root_search.py

[Feature] optimize root_search with masked_scatter_

---

torchdr/neighbor_embedding/umap.py

[BugFix] update docstring : spectral init not supported yet for umap

---

.gitignore
torchdr/affinity/base.py
torchdr/affinity/entropic.py
torchdr/affinity/knn_normalized.py
torchdr/affinity/quadratic.py
torchdr/affinity_matcher.py
torchdr/base.py
torchdr/neighbor_embedding/pacmap.py
torchdr/spectral_embedding/incremental_pca.py
torchdr/spectral_embedding/pca.py

[BugFix] set input data to compute device for PACMAP

---

torchdr/affinity/base.py
torchdr/affinity_matcher.py
torchdr/neighbor_embedding/base.py
torchdr/neighbor_embedding/infotsne.py
torchdr/neighbor_embedding/largevis.py
torchdr/neighbor_embedding/pacmap.py
torchdr/neighbor_embedding/umap.py

[Feature] Multi-GPU neighbor embedding

---

torchdr/affinity/knn_normalized.py
torchdr/neighbor_embedding/pacmap.py
torchdr/utils/sparse.py

[Feature] Distributed symmetrize sparse operation
